# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.user.provider:
        class: AppBundle\Security\User\UserProvider
        arguments: ["@app.user.handler"]

    app.user.handler:
        class: AppBundle\Handler\UserHandler
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

    app.authentication.handler:
        class: AppBundle\Handler\AuthenticationHandler
        arguments: ["@security.authorization_checker", "@router"]